### ISSUE TITLE
Flags: Find good solution

### ISSUE THREAD

**Issue by Briefmark** [jycr753/SF-bugs#74]
Oneplay wants the flags gone. But the flags indicate that the company should take notice of the user. Its their responsibility. 

What to do? @Nicolaj @Hachem

**Comment by jycr753** [comment]
Yep.... Totally agree if we remove this we need other way to manage user data

**Comment by Briefmark** [comment]
we are keeping flags as a quality control as long as we are only 'databehandler' and not 'dataansvarlig'
